# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
# 추천 시스템 테스트

POST http://127.0.0.1:8000/api/recommend
Content-Type: application/json

{
  "UserID": 1,
  "Gender": "Male",
  "Age_Group": "20-29",
  "Spicy_Preference": "Yes",
  "Allergies": "None",
  "Consumption_Size": "Large",
  "Previous_Orders": [1, 2, 3]
}

###
# 환영 인사 엔드포인트 테스트

GET http://127.0.0.1:8000/api/chatbot/greeting/1
Content-Type: application/json

###
# 챗봇 엔드포인트 테스트

POST http://127.0.0.1:8000/api/chatbot/1
Content-Type: application/json

{
  "message": "내 맵기 선호도, 먹는 양을 기반으로 버거 1개만 추천해줘."
}

###